USE codeup_test_db;
DROP TABLE IF EXISTS albums;

CREATE TABLE albums (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    artist VARCHAR(50) NOT NULL DEFAULT 'NONE',
    name VARCHAR(50) NOT NULL DEFAULT 'NONE',
    release_year DATE NOT NULL,
    sales DOUBLE NOT NULL,
    genre CHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
